# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: nekox
# Description of the Site
description: "Engineering ∩ Design"
# URL of Image of the Site
site-image: https://nekox.net/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Portfolio, Nekox
# URL for the Image of custom Favicon
favicon-url: https://nekox.net/favicon-32x32.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://nekox.net/assets/images/main-white.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mikan@nekox.net
facebook_username: 
twitter_username: mikanwolfe
instagram_username: 
linkedin_username: jtrac
github_username:  mikanwolfe
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
#  https://www.pixiv.net/en/users/
pixiv_username: 13646231
artstation_username:

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Mikanwolfe
# URL for the Image of the Author
author-image: https://avatars.githubusercontent.com/u/17631515
# 60 Words About the Author
author-about: "B. Mechatronics (Hons.) & B. Comp Sci (Software Design) @ Swinburne University of Technology"
author-about-sub: "Fundamentally design-driven engineer whose focus is on effective HMI interfaces and efficient data movement"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://nekox.net

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
